contact:
  path: /contactUs
  defaults: { _controller: InternalMarketingBundle:ContactUs:post }

estimator_purchase:
  path: /purchase
  defaults: { _controller: InternalMarketingBundle:EstimatorPurchase:post }